name: clear-cache
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["deploy"]
    types:
      - completed
jobs:
  clearcache:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: run curl
        run: |
           chmod +x ./update.sh
           ./update.sh
        env:
          cf_api: ${{ secrets.CF_API }}
          cf_zone: ${{ secrets.CF_ZONE }}
          header_api: ${{ secrets.HEADER_API }}
          http_response_header_id: ${{ secrets.HTTP_RESPONSE_HEADER_ID }}
          cf_task_id: ${{ secrets.CF_TASK_ID }}
        shell: bash
