name: generate words

# on:
#   schedule:
#     - cron: "30 6 * * *"    #runs at 6:30 UTC everyday

on: workflow_dispatch

jobs:
  refreshwords:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11 #install the python needed
      - name: execute py script
        run: |
          python -m pip install --upgrade pip
          python -m pip install requests
          python main.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto word updates"
          git push
          
  deploy:
      runs-on: ubuntu-latest
      needs: refreshwords
      permissions:
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: upload
          with:
            path: "./src"
          uses: actions/upload-pages-artifact@master
        - name: Deploy to GitHub Pages
          uses: actions/deploy-pages@v4

